### ISSUE TITLE
running fail with KeyError: 'voice'

### ISSUE THREAD

**Issue by chaojixiaoyao** [Harsha200105/DesktopAssistant#48]
Hi guys
When i  was first start which it crash.

Error information:
C:\Python39>python Jarvis2_4windows.py
Traceback (most recent call last):
  File "C:\Users\ckj\AppData\Local\Programs\Python\Python39\DesktopAssistant-main\DesktopAssistant-main\Jarvis2_4windows.py", line 6, in <module>
    from actions import (  # isort: skip
  File "C:\Users\ckj\AppData\Local\Programs\Python\Python39\DesktopAssistant-main\DesktopAssistant-main\actions.py", line 145, in <module>
    if config['DEFAULT']['voice'] == 'Male':
  File "C:\Users\ckj\AppData\Local\Programs\Python\Python39\lib\configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'voice'

**Comment by TallGorilla** [comment]
Can you please post the steps to reproduce this exception? 

I would like to have the following info to see what happened and fix the problem.
- [ ] which command were you trying to use?
- [ ] have you changed anything in the files after cloning the repo in your machine? If yes, what have you changed? Especially take a look at `jarvis_windows.py` and `config.ini`.

**Comment by Tejas3545** [comment]
hey can anyone tell me how to solve this problem i have same problem in the project that:
Traceback (most recent call last):
  File "c:\Users\solan\Downloads\0\DesktopAssistant-main\src\Jarvis2_4windows.py", line 7, in <module>
    from actions import (  # isort: skip
  File "c:\Users\solan\Downloads\0\DesktopAssistant-main\src\actions.py", line 146, in <module>
    if config['DEFAULT']['voice'] == 'Male':
       ~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\solan\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 1224, in __getitem__
    raise KeyError(key)
KeyError: 'voice'

i had tried many things in this like changing the config file , jarvis file, nsss.py file but nothing happened at last this error comes again so, why this problem coming? is this is a python version problem or a code mistake?
